# Generated by Django 4.1.7 on 2023-05-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='type',
            field=models.CharField(choices=[('C', 'Chronic'), ('N', 'Normal'), ('9C', '9C'), ('9T', '9T'), ('9R', '9R'), ('9E', '9E'), ('9D', '9D')], default='N', max_length=2),
        ),
    ]
